"""Markdown report formatting."""

from __future__ import annotations

from typing import Any

from lab.analyze.queries import summary_by_model_config, summary_by_model_simple


def _md_table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "_(no rows)_\n"
    keys = list(rows[0].keys())
    header = "| " + " | ".join(keys) + " |"
    sep = "| " + " | ".join(["---"] * len(keys)) + " |"
    body = []
    for r in rows:
        body.append(
            "| " + " | ".join("" if r.get(k) is None else str(r.get(k)) for k in keys) + " |"
        )
    return "\n".join([header, sep, *body]) + "\n"


def make_report(experiment_slug: str) -> str:
    by_model = summary_by_model_simple(experiment_slug)
    by_model_cfg = summary_by_model_config(experiment_slug)

    out: list[str] = [
        f"# Sweep report: `{experiment_slug}`",
        "",
        "_Generated by `lab analyze report`. Phase 1 metrics: counts, latency, tokens. "
        "Quality scoring lands in Phase 2 with evaluators._",
        "",
        "## Per-model summary",
        "",
        _md_table(by_model),
        "## Per-(model, config) summary",
        "",
        _md_table(by_model_cfg),
    ]
    return "\n".join(out)
