"""Markdown report formatting."""

from __future__ import annotations

from typing import Any

from lab.analyze.queries import (
    per_cell_results,
    summary_by_model_config,
    summary_by_model_simple,
    summary_eval_by_model,
)
from lab.analyze.stats import per_cell_stats, per_model_reliability


def _md_table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "_(no rows)_\n"
    keys = list(rows[0].keys())
    header = "| " + " | ".join(keys) + " |"
    sep = "| " + " | ".join(["---"] * len(keys)) + " |"
    body = []
    for r in rows:
        body.append(
            "| " + " | ".join("" if r.get(k) is None else str(r.get(k)) for k in keys) + " |"
        )
    return "\n".join([header, sep, *body]) + "\n"


def make_report(experiment_slug: str) -> str:
    by_model = summary_by_model_simple(experiment_slug)
    by_model_cfg = summary_by_model_config(experiment_slug)
    by_eval = summary_eval_by_model(experiment_slug)

    out: list[str] = [
        f"# Sweep report: `{experiment_slug}`",
        "",
        "_Generated by `lab analyze report`._",
        "",
        "## Per-model summary",
        "",
        _md_table(by_model),
        "## Per-(model, config) summary",
        "",
        _md_table(by_model_cfg),
        "## Evaluator pass rates",
        "",
        _md_table(by_eval) if by_eval else "_(no eval_results — run `lab eval apply` first)_\n",
    ]

    # If evaluators have been applied, include reliability summary for the most-applied evaluator
    if by_eval:
        primary = sorted({str(r["evaluator"]) for r in by_eval})[0]
        cells = per_cell_results(experiment_slug, primary)
        cell_stats = per_cell_stats(cells)
        reliability = per_model_reliability(cells)
        out.extend(
            [
                f"## Reliability (evaluator = `{primary}`)",
                "",
                "Per-model reliability summary (averaged across tasks):",
                "",
                _md_table(reliability),
                "Per-(model, task) pass^k:",
                "",
                _md_table(
                    [
                        {
                            "model": c.model,
                            "task": c.task,
                            "n": c.n,
                            "pass@1": round(c.pass_at_1, 3),
                            "pass^4": round(c.pass_caret_4, 3),
                            "pass^8": round(c.pass_caret_8, 3),
                            "ci_95": f"[{c.ci_lo:.2f}, {c.ci_hi:.2f}]",
                        }
                        for c in cell_stats
                    ]
                ),
            ]
        )

    return "\n".join(out)
