"""Markdown report formatting."""

from __future__ import annotations

from typing import Any

from lab.analyze.queries import (
    per_cell_results,
    summary_bfcl_emission,
    summary_by_model_config,
    summary_by_model_simple,
    summary_eval_by_model,
)
from lab.analyze.stats import per_cell_stats, per_model_reliability


def _md_table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "_(no rows)_\n"
    keys = list(rows[0].keys())
    header = "| " + " | ".join(keys) + " |"
    sep = "| " + " | ".join(["---"] * len(keys)) + " |"
    body = []
    for r in rows:
        body.append(
            "| " + " | ".join("" if r.get(k) is None else str(r.get(k)) for k in keys) + " |"
        )
    return "\n".join([header, sep, *body]) + "\n"


def _pass_rates_from_mlflow(experiment_slug: str) -> list[dict[str, Any]]:
    """Per-model pass rate from the MLflow `score` metric. Used for agent-path
    experiments, whose scores live in the trajectory footer -> MLflow rather
    than in eval_results. Best-effort: returns [] on any failure."""
    from collections import defaultdict

    try:
        import mlflow
        from mlflow.tracking import MlflowClient

        from lab.core.settings import get_settings

        mlflow.set_tracking_uri(get_settings().mlflow_url)
        exp = mlflow.get_experiment_by_name(experiment_slug)
        if exp is None:
            return []
        runs = MlflowClient().search_runs([exp.experiment_id], max_results=5000)
        agg: dict[str, list[float]] = defaultdict(list)
        for run in runs:
            sc = run.data.metrics.get("score")
            if sc is None:
                continue
            agg[run.data.tags.get("lab.model", "?")].append(float(sc))
        return [
            {
                "model": model,
                "evaluator": "score (MLflow)",
                "n": len(scores),
                "pass_rate": round(sum(scores) / len(scores), 3),
            }
            for model, scores in sorted(agg.items())
        ]
    except Exception:
        return []


def _eval_pass_rate_table(experiment_slug: str, by_eval: list[dict[str, object]]) -> str:
    if by_eval:
        return _md_table(by_eval)
    rows = _pass_rates_from_mlflow(experiment_slug)
    if rows:
        return (
            "_No `eval_results` for this experiment (agent-path scores live in "
            "MLflow). Pass rates from the MLflow `score` metric:_\n\n" + _md_table(rows)
        )
    return "_(no eval_results — run `lab eval apply` first)_\n"


def make_report(experiment_slug: str) -> str:
    by_model = summary_by_model_simple(experiment_slug)
    by_model_cfg = summary_by_model_config(experiment_slug)
    by_eval = summary_eval_by_model(experiment_slug)
    bfcl_emit = summary_bfcl_emission(experiment_slug)

    out: list[str] = [
        f"# Sweep report: `{experiment_slug}`",
        "",
        "_Generated by `lab analyze report`._",
        "",
        "## Per-model summary",
        "",
        _md_table(by_model),
        "## Per-(model, config) summary",
        "",
        _md_table(by_model_cfg),
        "## Evaluator pass rates",
        "",
        _eval_pass_rate_table(experiment_slug, by_eval),
    ]

    if bfcl_emit:
        out.extend(
            [
                "## BFCL function-calling decomposition",
                "",
                "_BFCL measures **function-calling**, not task-completion. A model that "
                "answers in prose emits no tool call and is a **non-emission**, not a wrong "
                "answer. `emit_rate_pct` = runs that emitted any tool call; "
                "`acc_given_emit_pct` = pass rate among those. A low `pass_rate_pct` driven "
                "by a low `emit_rate_pct` is a decode/format failure (e.g. a reasoning model "
                "under permissive `tool_choice`), **not** a capability gap \u2014 compare "
                "models on `acc_given_emit_pct`._",
                "",
                _md_table(bfcl_emit),
            ]
        )

    # If evaluators have been applied, include reliability summary for the most-applied evaluator
    if by_eval:
        primary = sorted({str(r["evaluator"]) for r in by_eval})[0]
        cells = per_cell_results(experiment_slug, primary)
        cell_stats = per_cell_stats(cells)
        reliability = per_model_reliability(cells)
        out.extend(
            [
                f"## Reliability (evaluator = `{primary}`)",
                "",
                "Per-model reliability summary (averaged across tasks):",
                "",
                _md_table(reliability),
                "Per-(model, task) pass^k:",
                "",
                _md_table(
                    [
                        {
                            "model": c.model,
                            "task": c.task,
                            "n": c.n,
                            "pass@1": round(c.pass_at_1, 3),
                            "pass^4": round(c.pass_caret_4, 3),
                            "pass^8": round(c.pass_caret_8, 3),
                            "ci_95": f"[{c.ci_lo:.2f}, {c.ci_hi:.2f}]",
                        }
                        for c in cell_stats
                    ]
                ),
            ]
        )

    return "\n".join(out)
